import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/Logos/Fav.png",
  },
};

import Footer from "@/components/Footer";
import TopBar from "@/components/TopBar";
import MainHeader from "@/components/MainHeader";
import TrustStrip from "@/components/TrustStrip";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} font-sans antialiased flex flex-col min-h-screen`}
      >
        <TopBar />
        <MainHeader />
        <TrustStrip />
        <main className="flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
